### ISSUE TITLE
Request to add the Configuration to select "Null" in the newline and newline_in_field config.

### ISSUE THREAD

**Issue by morihaya** [sonots/embulk-formatter-single_value#5]
Issue Type: New Feature Request (I quoted the embulk issue template)
--------------------------------

* Write your concrete practical scenarios with the new feature you want.

I want to use [embulk-parser-none](https://github.com/sonots/embulk-parser-none) and [embulk-formatter-single_value](https://github.com/sonots/embulk-formatter-single_value) to transfer a fixed length file, but I don't want to give a line break code at the end.

* Write your expectation how your suggestion helps others as well.

Embulk also allows for the handling of fixed-length files without line breaks. This will allow Embulk to replace older systems that deal with fixed-length telegrams. (If you can implement the function, we would like to introduce it on our company blog.)

The following is an image of its use.
```yaml
in:
  type: file
  path_prefix: ./FIXLENGTH
  file_ext: "DAT"
  parser:
    type: none
    column_name: payload
    charset: ASCII
out:
  type: file
  path_prefix: ./output
  file_ext: .dat
  sequence_format: ""
  formatter:
    charset: ASCII
    type: single_value
    column_name: payload
    null_string: ""
    newline: ""         <-- Here
    newline_in_field: "" <-- Here
```

Currently, the following error occurs, and it is necessary to add a new line and then add a new line.
> Error: org.embulk.config.ConfigException: java.lang.IllegalArgumentException: Can not construct instance of org.embulk.spi.util.Newline from String value '': value not one of declared Enum instance names: [CRLF, LF, CR]
